// backend/src/i18n/index.js
// Traductions FR / EN des documents générés (PDF, Excel…).
// Usage : const t = i18n.translator(lang);  t('status.APPROVED')  →  « Approuvé » / « Approved »
//         i18n.normalizeLang('en-US') → 'en'   (défaut : 'fr')

const fr = {
  status: {
    DRAFT: 'Brouillon',
    PENDING: 'En attente',
    PENDING_APPROVAL: "En attente d'approbation",
    BUDGET_CHECKED: 'Budget vérifié',
    BUDGET_INSUFFICIENT: 'Budget insuffisant',
    APPROVED: 'Approuvée',
    REJECTED: 'Rejetée',
    IN_PROGRESS: 'En cours',
    COMPLETED: 'Terminée',
    CANCELLED: 'Annulée',
    CLASSIFIED_DIRECT_PURCHASE: 'Achat direct',
    CLASSIFIED_MULTIPLE_QUOTATIONS: 'Devis multiples',
    CLASSIFIED_RFP: "Appel d'offres",
    CLASSIFIED_SOLE_SOURCE: 'Source unique',
  },
  progress: {
    DRAFT: 'Brouillon',
    IN_PROGRESS: 'En cours',
    COMPLETED: 'Terminé',
    REJECTED: 'Rejeté',
    CANCELLED: 'Annulé',
  },
  priority: { LOW: 'Basse', MEDIUM: 'Moyenne', HIGH: 'Haute', URGENT: 'Urgente' },
  requisition: {
    docTitle: 'Réquisition',
    generatedOn: 'Généré le {date} à {time}',
    title: 'Titre',
    step: 'Étape',
    progress: 'Avancement',
    department: 'Département',
    project: 'Projet',
    estimatedAmount: 'Montant estimé',
    priority: 'Priorité',
    requester: 'Demandeur',
    createdAt: 'Date de création',
    description: 'Description',
    justification: 'Justification',
    items: 'Articles',
    itemDescription: 'Description',
    quantity: 'Quantité',
    frequency: 'Fréquence',
    unitPrice: 'Prix unitaire',
    total: 'Total',
    grandTotal: 'Total général',
    budgetLine: 'Ligne budgétaire',
    attachments: 'Pièces jointes',
    bytes: 'octets',
    footer: '{enterprise} — document généré automatiquement par {app}',
    taxId: 'NIF',
    registration: 'RCCM',
  },
};

const en = {
  status: {
    DRAFT: 'Draft',
    PENDING: 'Pending',
    PENDING_APPROVAL: 'Pending approval',
    BUDGET_CHECKED: 'Budget checked',
    BUDGET_INSUFFICIENT: 'Insufficient budget',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    IN_PROGRESS: 'In progress',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    CLASSIFIED_DIRECT_PURCHASE: 'Direct purchase',
    CLASSIFIED_MULTIPLE_QUOTATIONS: 'Multiple quotations',
    CLASSIFIED_RFP: 'Call for tenders (RFP)',
    CLASSIFIED_SOLE_SOURCE: 'Sole source',
  },
  progress: {
    DRAFT: 'Draft',
    IN_PROGRESS: 'In progress',
    COMPLETED: 'Completed',
    REJECTED: 'Rejected',
    CANCELLED: 'Cancelled',
  },
  priority: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High', URGENT: 'Urgent' },
  requisition: {
    docTitle: 'Purchase requisition',
    generatedOn: 'Generated on {date} at {time}',
    title: 'Title',
    step: 'Step',
    progress: 'Progress',
    department: 'Department',
    project: 'Project',
    estimatedAmount: 'Estimated amount',
    priority: 'Priority',
    requester: 'Requester',
    createdAt: 'Created on',
    description: 'Description',
    justification: 'Justification',
    items: 'Items',
    itemDescription: 'Description',
    quantity: 'Quantity',
    frequency: 'Frequency',
    unitPrice: 'Unit price',
    total: 'Total',
    grandTotal: 'Grand total',
    budgetLine: 'Budget line',
    attachments: 'Attachments',
    bytes: 'bytes',
    footer: '{enterprise} — document automatically generated by {app}',
    taxId: 'Tax ID',
    registration: 'Company reg. no.',
  },
};

const DICTS = { fr, en };
const LOCALES = { fr: 'fr-FR', en: 'en-GB' };

function normalizeLang(lang) {
  const l = String(lang || '').toLowerCase().slice(0, 2);
  return DICTS[l] ? l : 'fr';
}

/** t('status.APPROVED', { var: … }) ; clé inconnue → dernière partie de la clé (ex. le code du statut) */
function translator(lang) {
  const dict = DICTS[normalizeLang(lang)];
  return (key, vars = {}) => {
    const value = key.split('.').reduce((o, k) => (o == null ? undefined : o[k]), dict);
    const text = typeof value === 'string' ? value : key.split('.').pop();
    return text.replace(/\{(\w+)\}/g, (m, v) => (vars[v] !== undefined ? vars[v] : m));
  };
}

module.exports = { normalizeLang, translator, locale: (lang) => LOCALES[normalizeLang(lang)], LANGS: Object.keys(DICTS) };
