import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Save, FileText } from 'lucide-react';
import toast from 'react-hot-toast';
import { invoiceService } from '../../services/invoiceService';
import api from '../../services/api';
import { useCurrency } from '../../contexts/EnterpriseContext';
import { t, getLocale } from '../../i18n';

export default function InvoiceForm() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const poId   = searchParams.get('poId');
  const grnId  = searchParams.get('grnId');
  const taskId = searchParams.get('taskId');

  const { currency } = useCurrency();
  const [po, setPO] = useState(null);
  const [suppliers, setSuppliers] = useState([]);
  const [currencies, setCurrencies] = useState([]);
  const [loading, setLoading] = useState(false);

  const [form, setForm] = useState({
    invoiceNumber: '',
    invoiceDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    subtotal: '',
    taxAmount: '0',
    totalAmount: '',
    currency: '',
    notes: '',
    supplierId: '',
    poId: poId || '',
    grnId: grnId || ''
  });

  useEffect(() => {
    api.get('/currencies').then(r => setCurrencies(r.data?.data || [])).catch(() => {});
    api.get('/suppliers').then(r => setSuppliers(r.data?.data || [])).catch(() => {});
  }, []);

  useEffect(() => {
    if (currency.code && !form.currency) {
      setForm(f => ({ ...f, currency: currency.code }));
    }
  }, [currency.code]);

  useEffect(() => {
    if (!poId) return;
    api.get(`/purchase-orders/${poId}`)
      .then(r => {
        const d = r.data?.data;
        setPO(d);
        setForm(f => ({
          ...f,
          supplierId: d?.supplier_id || '',
          currency: d?.currency || currency.code || '',
          totalAmount: d?.total_amount || '',
          subtotal: d?.total_amount || ''
        }));
      })
      .catch(() => {});
  }, [poId]);

  function set(field, value) {
    setForm(f => {
      const next = { ...f, [field]: value };
      // Auto-compute total
      if (field === 'subtotal' || field === 'taxAmount') {
        next.totalAmount = (parseFloat(next.subtotal || 0) + parseFloat(next.taxAmount || 0)).toFixed(2);
      }
      return next;
    });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    if (!form.totalAmount || !form.invoiceDate) {
      toast.error(t('invoice.amountDateRequired'));
      return;
    }
    setLoading(true);
    try {
      const res = await invoiceService.create({
        ...form,
        taskId: taskId || undefined,
        poId: form.poId || undefined,
        grnId: form.grnId || undefined,
        supplierId: form.supplierId || undefined
      });
      if (res.success) {
        const matchLabel = res.data.match_status === 'MATCHED' ? t('invoice.matchedLabel') : `⚠️ ${t(`matchStatus.${res.data.match_status}`, { defaultValue: res.data.match_status })}`;
        toast.success(t('invoice.created', { match: matchLabel }));
        navigate(`/invoices/${res.data.id}`);
      } else {
        toast.error(res.message || t('invoice.createError'));
      }
    } catch (e) {
      toast.error(e.response?.data?.message || t('po.createError'));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="p-6 max-w-2xl mx-auto">
      <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-6 text-sm">
        <ArrowLeft size={16} /> {t('common.back')}
      </button>

      <div className="flex items-center gap-3 mb-6">
        <FileText size={28} className="text-blue-600" />
        <div>
          <h1 className="text-xl font-bold text-gray-900">{t('invoice.newTitle')}</h1>
          {po && <p className="text-gray-500 text-sm">{t('grn.poRef', { number: po.po_number, supplier: po.supplier_name })}</p>}
        </div>
      </div>

      {po && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-6 text-sm grid grid-cols-3 gap-3">
          <div><span className="text-blue-600 font-medium">PO</span><br />{po.po_number}</div>
          <div><span className="text-blue-600 font-medium">{t('invoice.poAmount')}</span><br />{parseFloat(po.total_amount || 0).toLocaleString(getLocale())} {po.currency}</div>
          <div><span className="text-blue-600 font-medium">{t('invoice.linkedGrn')}</span><br />{grnId ? `GRN #${grnId}` : '—'}</div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="bg-white border border-gray-200 rounded-xl p-6 space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('invoice.supplierNumber')}</label>
            <input
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder={t('invoice.autoGenerated')}
              value={form.invoiceNumber}
              onChange={e => set('invoiceNumber', e.target.value)}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('common.supplier')}</label>
            <select
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={form.supplierId}
              onChange={e => set('supplierId', e.target.value)}
            >
              <option value="">{t('common.select')}</option>
              {suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('invoice.invoiceDateRequired')}</label>
            <input type="date" required
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={form.invoiceDate}
              onChange={e => set('invoiceDate', e.target.value)}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('invoice.dueDateLabel')}</label>
            <input type="date"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={form.dueDate}
              onChange={e => set('dueDate', e.target.value)}
            />
          </div>
        </div>

        <div className="grid grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('invoice.subtotalRequired')}</label>
            <input type="number" min="0" step="0.01" required
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={form.subtotal}
              onChange={e => set('subtotal', e.target.value)}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('invoice.tax')}</label>
            <input type="number" min="0" step="0.01"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={form.taxAmount}
              onChange={e => set('taxAmount', e.target.value)}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('invoice.totalRequired')}</label>
            <input type="number" min="0" step="0.01" required
              className="w-full border border-blue-300 bg-blue-50 rounded-lg px-3 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={form.totalAmount}
              onChange={e => set('totalAmount', e.target.value)}
            />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('common.currency')}</label>
            <select
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
              value={form.currency}
              onChange={e => set('currency', e.target.value)}
            >
              {currencies.length > 0
              ? currencies.map(c => <option key={c.id} value={c.format_key}>{c.format_key} — {c.name}</option>)
              : <option value={currency.code}>{currency.code}</option>}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('invoice.poNumber')}</label>
            <input
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm bg-gray-50"
              value={form.poId}
              readOnly
              placeholder={t('invoice.notLinked')}
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">{t('common.notes')}</label>
          <textarea rows={2}
            className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            value={form.notes}
            onChange={e => set('notes', e.target.value)}
          />
        </div>

        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 text-xs text-yellow-800">
          {t('invoice.matchHint')}
        </div>

        <div className="flex gap-3 pt-2">
          <button type="button" onClick={() => navigate(-1)}
            className="px-4 py-2 border border-gray-300 rounded-lg text-sm hover:bg-gray-50">
            {t('common.cancel')}
          </button>
          <button type="submit" disabled={loading}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white px-6 py-2 rounded-lg text-sm font-medium">
            {loading ? t('po.saving') : <><Save size={16} /> {t('invoice.saveAndMatch')}</>}
          </button>
        </div>
      </form>
    </div>
  );
}
